version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "daily"
    assignees:
      - "klen"

  # Maintain dependencies for Python
  - package-ecosystem: "uv"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "daily"
    assignees:
      - "klen"

  # Maintain dependencies for Javascript
  - package-ecosystem: "npm"
    directory: "/frontend"
    labels:
      - dependencies
    schedule:
      interval: "daily"
    assignees:
      - "klen"
