# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@main

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Setup dependencies
        run: uv sync --locked --all-extras --dev

      - name: Check code
        run: uv run ruff check muffin_admin

      - name: Check typing
        run: uv run mypy

      - name: Test with pytest
        run: uv run pytest tests
