# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:

    - name: Checkout changes
      uses: actions/checkout@v2.3.4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache env
      id: cache-env
      uses: actions/cache@v2
      with:
        path: env
        key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}

    - name: Install requirements
      run: |
        python -m venv env
        env/bin/pip install -e .[tests]
      if: steps.cache-env.outputs.cache-hit != 'true'

    - name: Test with pytest
      run: env/bin/pytest tests
